name: Gradle test On GitHub Action
on:
  push:
    branches-ignore: [ 'main','master','rkaehdaos' ]

jobs:
  onPushTest:
    if: github.event.pull_request.opened == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@master

      - name: setup-java-21
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '11'
          cache: 'gradle'

      - name: test
        run: |
          echo "Available processors: $(nproc)"
          gradle test jacocoTestCoverageVerification --no-daemon --parallel

      - name: Extract coverage info and update step summary
        run: |
          echo 'CSV 파일에서 커버리지 정보 추출';
          awk -F',' 'NR > 1 {instructions_covered += $5; instructions_missed += $4; branches_covered += $7; branches_missed += $6} END {print instructions_covered, instructions_missed, branches_covered, branches_missed}' build/reports/jacoco/test/jacocoTestReport.csv > coverage.txt
          read instructions_covered instructions_missed branches_covered branches_missed < coverage.txt               
          echo '커버리지 계산'; 
          total_instructions=$((instructions_covered + instructions_missed))
          total_branches=$((branches_covered + branches_missed))
          instruction_coverage=$(echo "scale=2; $instructions_covered / $total_instructions * 100" | bc)
          echo '분모가 0일 경우, 커버리지를 'N/A'로 설정';
          if [ "$total_instructions" -eq 0 ]; then
            instruction_coverage="N/A"
          else
            instruction_coverage=$(echo "scale=2; $instructions_covered / $total_instructions * 100" | bc)%
          fi
          if [ "$total_branches" -eq 0 ]; then
            branch_coverage="N/A"
          else
            branch_coverage=$(echo "scale=2; $branches_covered / $total_branches * 100" | bc)%
          fi
          echo 'GITHUB_STEP_SUMMARY에 커버리지 정보 추가';
          echo "JaCoCo 커버리지 요약" >> $GITHUB_STEP_SUMMARY
          echo "Instruction Coverage: $instruction_coverage" >> $GITHUB_STEP_SUMMARY
          echo "Branch Coverage: $branch_coverage" >> $GITHUB_STEP_SUMMARY

      - name: Upload JaCoCo coverage report
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

      - name: Notification
        uses: 8398a7/action-slack@v3
        if: always()
        with:
          status: ${{ job.status }}
          author_name: GeunChang Ahn
          job_name: onPushTest
          fields: repo,message,commit,author,eventName,ref,workflow,job,took,
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}